### ISSUE TITLE
w/o ASL, how to generate Modal specific graph in eq.(8) for ablation study?

### ISSUE THREAD

**Issue by xinzhou-ai** [HKUDS/MMSSL#9]
Thanks for sharing your code~ Could I have your help on how to perform ablation study w/o ASL (better with implementation code). Thanks.

**Comment by weiwei1206** [comment]
Thank you very much for your interest in our work!

Are you the author of BM3? I have read your work and your work is excellent. The code is also very easy to understand. 

In our new work, we have taken your BM3 as the baseline.

It seems that you have raised many questions about our work. I noticed earlier that you asked many questions under different accounts.

I will try to address your concerns ~

This is the ablation experiment of our self-enhancement module. It aims to inject more collaborative signals into modality-specific features, otherwise it would just contain more item-end content but not modality-aware user preference. Therefore, it eliminates the adversarial training part. 
In fact, our recommender is used as a generator, and its purpose is to enable the item-end feature output by the encoder to establish dependencies between modality-specific content and collaborative signals when encoding information. This process will be constrained by the loss of the generator. Therefore, if you want to obtain the results of the ablation experiment, you can try to comment out the loss function of the generator and the modality-specific GNN. For the ablation experiment of this module, we achieved the best experimental results on TikTok. If this module is removed, the training will collapse.
